services:
  _defaults:
    public: true
    
  mpstockservice.controller.admin.product_stock_service:
    class: MpSoft\MpStockService\Controllers\Admin\ProductStockServiceController
    arguments:
      - '@prestashop.core.admin.data_provider.product_interface'
      - '@prestashop.adapter.legacy.context'
    tags:
      - { name: controller.service_arguments }
